<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ae\x0A\x0Cperson.proto\"M\x0A\x0DSearchRequest\x12\x0D\x0A\x05query\x18\x01 \x01(\x09\x12\x13\x0A\x0Bpage_number\x18\x02 \x01(\x05\x12\x18\x0A\x10results_per_page\x18\x03 \x01(\x05b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

/**
 * Generated from protobuf message <code>SearchRequest</code>
 */
class SearchRequest extends Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string query = 1;</code>
     */
    protected $query = '';
    /**
     * Generated from protobuf field <code>int32 page_number = 2;</code>
     */
    protected $page_number = 0;
    /**
     * Generated from protobuf field <code>int32 results_per_page = 3;</code>
     */
    protected $results_per_page = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $query
     *     @type int $page_number
     *     @type int $results_per_page
     * }
     */
    public function __construct($data = NULL) {
        Person::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_number = 2;</code>
     * @return int
     */
    public function getPageNumber()
    {
        return $this->page_number;
    }

    /**
     * Generated from protobuf field <code>int32 page_number = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 results_per_page = 3;</code>
     * @return int
     */
    public function getResultsPerPage()
    {
        return $this->results_per_page;
    }

    /**
     * Generated from protobuf field <code>int32 results_per_page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setResultsPerPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->results_per_page = $var;

        return $this;
    }

}

