<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto

namespace GPBMetadata;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ae\x0A\x0Cperson.proto\"M\x0A\x0DSearchRequest\x12\x0D\x0A\x05query\x18\x01 \x01(\x09\x12\x13\x0A\x0Bpage_number\x18\x02 \x01(\x05\x12\x18\x0A\x10results_per_page\x18\x03 \x01(\x05b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

